### ISSUE TITLE
[Deno support] Adapter 'http' is not available in the build

### ISSUE THREAD

**Issue by isaced** [joyqi/node-openai#2]
Here is my code:

```typescript
import { OpenAI } from "https://esm.sh/node-openai@0.4.2";

const openai = new OpenAI({
    apiKey:"XXX"
});
const api = openai.v1();
await api.chat.create({
    model: 'gpt-3.5-turbo',
    messages: [
        {
            role: 'user',
            content: 'Hello, how are you?'
        }
    ]
});
```

got error:

```
[uncaught application error]: Error - Adapter 'http' is not available in the build
   at Object.getAdapter (https://esm.sh/v111/axios@1.3.4/deno/axios.js:4:5896)
    at _.te (https://esm.sh/v111/axios@1.3.4/deno/axios.js:4:6410)
    at _.request (https://esm.sh/v111/axios@1.3.4/deno/axios.js:4:9987)
    at https://esm.sh/v111/axios@1.3.4/deno/axios.js:2:206
    at https://esm.sh/v111/node-openai@0.4.2/deno/node-openai.js:2:3301
    at Object.create (https://esm.sh/v111/node-openai@0.4.2/deno/node-openai.js:2:369)
    at sendMessage (file:///Users/xxx/Projects/xxxxxx/services.ts:19:27)
```

ENV:

> deno 1.31.1 (release, x86_64-apple-darwin)
> v8 11.0.226.13
> typescript 4.9.4

**Comment by joyqi** [comment]
Seems like axios is not compatible with deno. Perhaps we can use fetch instead?

**Comment by isaced** [comment]
Yes, I think it would be better to use `fetch()`.

**Comment by joyqi** [comment]
I'm still working on it. There're some issues with FormData.

**Comment by joyqi** [comment]
Try `0.5.0` instead, I've created a abstract layer to handle http request.

**Comment by isaced** [comment]
Great, it works now. 👍
